Repository minetest-mods/teleport-request, pull requests merged in 2020-01, with the labels that each got.

#20 Fix crashing when unknown nodes are near
  init.lua
Labels: Bugfix, High priority, One approval, Review required

#21 Fix compatibility with beerchat muting
  init.lua
Labels: Bugfix, High priority, One approval

#24 Divide commands, privileges and functions into various files
  commands.lua
  config.lua
  functions.lua
  init.lua
  privileges.lua
Labels: Low priority, Maintenance, One approval

#25 Add Factorio Luacheck action
  .github/workflows/check-release.yml
  .luacheckrc
  README.md
  config.lua
  functions.lua
  init.lua
Labels: Enhancement, Maintenance, Medium priority, One approval, Testing needed

#27 Fix protection check
  functions.lua
Labels: Bugfix, High priority, One approval

#28 Fix positional sound
  functions.lua
  sounds/whoosh.ogg
Labels: Audiovisuals, Bugfix, One approval

#29 Add new warp sound
  README.md
  functions.lua
  init.lua
  sounds/LICENSE.txt
  sounds/tpr_warp.ogg
  sounds/whoosh.ogg
Labels: Audiovisuals, Medium priority, One approval
