Repository minetest-mods/teleport-request, pull requests merged in 2021-08, with the labels that each got.

#45 Fix indentation
  functions.lua
Labels: Maintenance

#47 Fix chat
  config.lua
  functions.lua
  settingtypes.txt
Labels: Bugfix :white_check_mark:, Maintenance

#48 Fix tp snipe simple
  functions.lua
Labels: Enhancement :gear:, High priority :exclamation:

#44 Add short contributing guidelines
  CONTRIBUTING.md
Labels: Documentation :gear:, One approval :heavy_check_mark:
